# This file is automatically generated by CMake to include the tests for the target boost_beast2_tests.
# It includes the tests from the file C:/dev/repos/MungoG/cursor_boost/libs/beast2/bin64/test/unit/boost_beast2_tests-da39a3e_tests.cmake.
if (EXISTS "C:/dev/repos/MungoG/cursor_boost/libs/beast2/bin64/test/unit/boost_beast2_tests-da39a3e_tests.cmake")
    include("C:/dev/repos/MungoG/cursor_boost/libs/beast2/bin64/test/unit/boost_beast2_tests-da39a3e_tests.cmake")
else()
    # If the tests file does not exist, create a dummy test to avoid errors.
    # The tests file will not exist if we have not run the cmake build step yet.
    add_test(boost_beast2_tests_NOT_BUILT-da39a3e boost_beast2_tests_NOT_BUILT-da39a3e)
endif ()
