# This file is automatically generated by CMake to include the tests for the target boost_capy_tests.
# It includes the tests from the file /home/mungo/winrepos/MungoG/cursor_boost/libs/beast2/build-wsl/Dependencies/boost/libs/capy/test/unit/boost_capy_tests-da39a3e_tests.cmake.
if (EXISTS "/home/mungo/winrepos/MungoG/cursor_boost/libs/beast2/build-wsl/Dependencies/boost/libs/capy/test/unit/boost_capy_tests-da39a3e_tests.cmake")
    include("/home/mungo/winrepos/MungoG/cursor_boost/libs/beast2/build-wsl/Dependencies/boost/libs/capy/test/unit/boost_capy_tests-da39a3e_tests.cmake")
else()
    # If the tests file does not exist, create a dummy test to avoid errors.
    # The tests file will not exist if we have not run the cmake build step yet.
    add_test(boost_capy_tests_NOT_BUILT-da39a3e boost_capy_tests_NOT_BUILT-da39a3e)
endif ()
